### ISSUE TITLE
Package not available on Melpa

### ISSUE THREAD

**Issue by I2obiN** [hlissner/evil-multiedit#57]
### What did you expect to happen?

M-x package-install RET evil-multiedit

no sign of the package

### What actually happened?

package not available

### Steps to reproduce

attempt step 1 of installation

### Package commit

no idea

### System Information

mac os homebrew install

**Comment by I2obiN** [comment]
for the love of god put up a sign that this is deprecated.

**Comment by hlissner** [comment]
`M-x package-install RET evil-multiedit` works fine for me? What should be deprecated?

Did you forget to load the package after installing it?

**Comment by hlissner** [comment]
I'll close this since it's clearly pilot error.

**Comment by I2obiN** [comment]
Fresh install of doom-emacs it was not listed in packages, evil-mc was there but evil-multiedit just was not on the list of packages

**Comment by hlissner** [comment]
Ah, I think I understand the problem. `M-x package-install` will omit packages that it believes are already installed (via `M-x package-install` only), and Doom doesn't use Emacs' internal package manager (package.el) so unless you've set it up yourself, it won't "remember" what packages you've installed with it between Emacs sessions.

You can confirm this by checking to see if `evil-multiedit` shows up in the menu for `M-x package-delete`.

In any case, you should avoid `M-x package-install` in Doom Emacs, unless you have a good reason not to and know how to set up package.el yourself, because Doom comes with its own package manager. The canonical way to (permanently) install a package in Doom is to add this to `$DOOMDIR/packages.el` (e.g. `~/.config/doom/packages.el`):

```elisp
(package! evil-multiedit)
```

Then run `$EMACSDIR/bin/doom sync` in your terminal, then restart Emacs.

Alternatively, Doom's `:editor multiple-cursors` module installs and configures `evil-multiedit` for you, so enabling that (by uncommenting it in your `doom!` block in `$DOOMDIR/init.el`) will accomplish the same. (Don't forget to run `doom sync` after doing this, as well)

Hope that helps!

**Comment by I2obiN** [comment]
yeh it's in M-x package-delete. I had added to packages.el trying to get it to work but was still getting errors on keybinds. That is pretty strange behaviour on package-installs part to omit already installed packages, I mean we're checking for installed packages via a delete command which is very counter-intuitive but I'm guessing that is down to emacs

i did end up enabling multiple-cursors in the end and when I left it I had it working on the R keybind in visual

If the norm is to avoid package-install and configure multiple-cursors then the readme could use a rewrite. the important configuration part is just under a section 'Doom-Emacs' and the 'Installation' is completely optional from my understanding here

**Comment by hlissner** [comment]
> That is pretty strange behaviour on package-installs part to omit already installed packages, I mean we're checking for installed packages via a delete command which is very counter-intuitive but I'm guessing that is down to emacs

What you want is `M-x package-list-packages`. I simply suggested using `M-x package-delete` as a shortcut to double check my suspicion (because `package-list-packages` produces a giant list of all available and installed packages, which would take longer for you to skim or understand, which could've complicated the debugging process for this issue).

> If the norm is to avoid package-install and configure multiple-cursors then the readme could use a rewrite. the important configuration part is just under a section 'Doom-Emacs' and the 'Installation' is completely optional from my understanding here

The norm for Doom users is to enable its `:editor multiple-cursors` module or use `package!` statements, but the norm for Emacs (non-Doom users) is use to `M-x package-install`. There are more non-Doom users than Doom users, that's why it's the first entry in the Installation section, and this package wasn't made solely for Doom's users.

I'll try to make the readme clearer, but you should understand this practice now, because you'll find most Emacs packages will do this in their READMEs (that is, having separate install instructions for the various Emacs starter kits *after* the more general `M-x package-install` (or `use-package`) approach).
